- name: Run with inline v2 compose
  hosts: emc23-4
  connection: local
  gather_facts: no
  tasks:
    - pip:
        name: "{{ item }}"
      with_items:
      - setuptools
      - six==1.4
      - docker-py

    - docker_service:
        project_name: RPS
        definition:
          version: '2'
          services:
            db:
              image: techbot/mysql
              volumes:
                - "./.data/db:/var/lib/mysql"
              restart: always
              environment:
                MYSQL_ROOT_PASSWORD: wordpress
                MYSQL_DATABASE: wordpress
                MYSQL_USER: wordpress
                MYSQL_PASSWORD: wordpress
              volumes:
                      - "./html:/var/www/html"
                      - "./src:/var/www/src"
                      - "./app:/var/www/app"
                      - "./bin:/var/www/bin"
                      - "./var:/var/www/var"
                      - "./vendor:/var/www/vendor"
                      - ./site.conf:/etc/nginx/conf.d/default.conf

            phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: myadmin
                environment:
                 - PMA_ARBITRARY=1
                 - PMA_HOST=mysqlserver phpmyadmin/phpmyadmin
                restart: always
                ports:
                 - 8080:80

            web:
                 image: techbot/rock-paper-scissors-react-redux