version: '2'
services:
  db:
    image: techbot/mysql
    ports:
    - "3306:3306"
    links:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    image: techbot/rock-paper-scissors-react-redux
    ports:
      - "80:80"

  eventstore:
    image: techbot/docker-event
    ports:
       - "2113:2113"









