web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - "./.data/db:/var/lib/mysql"
        - "./html:/var/www/html"
        - "./src:/var/www/src"
        - "./app:/var/www/app"
        - "./bin:/var/www/bin"
        - "./var:/var/www/var"
        - "./vendor:/var/www/vendor"
        - "./site.conf:/etc/nginx/conf.d/site.conf"
    links:
        - php
    volumes_from:
        - php
php:
    image: php:7-fpm
    volumes:
     - "./.data/db:/var/lib/mysql"
     - "./html:/var/www/html"
     - "./src:/var/www/src"
     - "./app:/var/www/app"
     - "./bin:/var/www/bin"
     - "./var:/var/www/var"
     - "./vendor:/var/www/vendor"

